version: "3"

services:
  database:
    container_name: postgres
    image: postgres:13.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=marketplace-flowers
    ports:
      - "5432:5432"
    volumes:
      - ./database_postgresql:/var/lib/postgresql/data 
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
  backend:
    container_name: backend
    build:
       context: ./backend
       dockerfile: Dockerfile
    # depends_on:
    #   - database   
    command: npm run start:dev    
    ports:
      - '5000:5000'
    working_dir: /usr/src/app
    restart: unless-stopped
  frontend:
    container_name: frontend
    restart: always  
    working_dir: /usr/src/app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - '3000:3000'  
